export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST";
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS";
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE";

export const EMAIL_LOGIN_REQUEST = "EMAIL_LOGIN_REQUEST";
export const EMAIL_LOGIN_SUCCESS= "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_FAILURE = "EMAIL_LOGIN_FAILURE";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";
