export const LOG_OUT = "LOG_OUT";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST";
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS";
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE";

export const EMAIL_LOGIN_REQUEST = "EMAIL_LOGIN_REQUEST";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_FAILURE = "EMAIL_LOGIN_FAILURE";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";

//Cart and Wishlist Functionality
export const MODIFY_ITEM_SIZE = "MODIFY_ITEM_SIZE";
export const MODIFY_ITEM_QUANTITY = "MODIFY_ITEM_QUANTITY";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const MAKE_CART_EMPTY = "MAKE_CART_EMPTY";

export const REMOVE_WISHLIST_ITEM = "REMOVE_WISHLIST_ITEM";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
